name: Reliable Pull Request Action
description: Creates a pull request on a GitHub repository using existing branches
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  title:
    description: 'Pull Request Title'
    required: true
  sourceBranch:
    description: 'Source Branch Name'
    required: true
  targetBranch:
    description: 'Target Branch Name'
    required: true
  body:
    description: 'Pull Request Body'
    required: false
  labels:
    description: 'Labels (comma-separated)'
    required: false
  assignees:
    description: 'Assignees (comma-separated)'
    required: false
outputs:
  PRURL:
    description: 'The URL of the created pull request'
runs:
  using: 'composite'
  steps:
    - name: Create Pull Request
      shell: bash
      run: |
        PR_OUTPUT=$(gh pr create \
        --title "${{ inputs.title }}" \
        --body "${{ inputs.body }}" \
        --base "${{ inputs.targetBranch }}" \
        --head "${{ inputs.sourceBranch }}" \
        --label "${{ inputs.labels }}" \
        --assignee "${{ inputs.assignees }}")

        # Extract PR URL from the output
        PR_URL=$(echo "$PR_OUTPUT" | grep -o 'https://github.com/[^ ]*')

        # Set the PR URL as the output
        echo "name=$PR_URL" >> $GITHUB_OUTPUT
